### ISSUE TITLE
When registering a message handler for an event you have use the event id as method id

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/vsomeip#109]
`event_t` and `method_t` are both `uint16_t`, so the type matches, but the semantics of the `register_message_handler` signature do not make it clear, that an event_id is implicitly a method_id.
Maybe change `typedef uint16_t event_t; ` to ` typedef method_t event_t;` ? Or merge `event_t` and `method_t` into one type?

**Comment by lutzbichler** [comment]
The SOME/IP specification states "Method ID, which is also called Event ID". However, maybe we will simply remove "event_t" in the future.
