### ISSUE TITLE
Is there any problem in communication between vsomeip3  stack and old vsomeip stack？

### ISSUE THREAD

**Issue by xuguoxuan** [GENIVI/vsomeip#110]
I have two devices，one with vsomeip3 stack and another one with an old vsomeip stack(v2.14.16), now I want to I want these two devices to communicate with each other through the someip protocol, is there any problem of that? Please give me some official advice, thanks very much.

**Comment by lutzbichler** [comment]
Yes, selective events (that are no official part of SOME/IP) are incompatible. Everything else is expected to work.
