### ISSUE TITLE
Is Vsomeip capable of reassembly UDP fragmented packages?

### ISSUE THREAD

**Issue by cjs102** [GENIVI/vsomeip#118]
Hello, i have studied very closely the code of vsomeip and i have found some functions, classes, etc (tp, tp_message, and tp_reassembler) that basically includes functions to split and reconstruct UDP messages. Right now there is no documention or examples (other than the tests) about how to do this. 

Will vsomeip be capable of such thing in the near future? If so, when?

Thanks in advance.

**Comment by ManuelKugelmann** [comment]
Look into the user guide [https://github.com/GENIVI/vsomeip/blob/master/documentation/vsomeipUserGuide](url) for the necessary configuration for the SOME/IP-TP feature.
If the tests work, it should be ready for use...

**Comment by lutzbichler** [comment]
SOME/IP-TP is implemented in v3 and its usage (as was pointed already pointed out by @ManuelKugelmann) is documented in the user guide. There no examples other than the tests available.
