### ISSUE TITLE
code error???

### ISSUE THREAD

**Issue by xiaostang** [GENIVI/vsomeip#122]
![image](https://user-images.githubusercontent.com/32772277/79710276-193a3700-82f7-11ea-8db1-b2cae723906e.png)
in file routing_manger_stub.cpp .   std::bind(&routing_manager_stub::client_registration_func, this));
in this place , if this should be shared_from_this()???

**Comment by lutzbichler** [comment]
The thread is controlled from the object itself (by start/stop) and the object is controlled from the routing manager. Therefore, the object will never be deleted without having called stop.
