### ISSUE TITLE
[COMPAT][BUILD][Windows] build error if VSOMEIP_ENABLE_COMPAT is activated

### ISSUE THREAD

**Issue by enarouge** [GENIVI/vsomeip#131]
`
1>F:\GIT\vsomeip\implementation\compat\runtime\src\runtime.cpp(12): warning C4273: 'vsomeip::runtime::get_property' : liaison DLL incohérente
1>F:\GIT\vsomeip\interface\compat/vsomeip/runtime.hpp(53): note: voir la définition précédente de 'get_property'
1>F:\GIT\vsomeip\implementation\compat\runtime\src\runtime.cpp(18): warning C4273: 'vsomeip::runtime::set_property' : liaison DLL incohérente
1>F:\GIT\vsomeip\interface\compat/vsomeip/runtime.hpp(54): note: voir la définition précédente de 'set_property'
1>F:\GIT\vsomeip\implementation\compat\runtime\src\runtime.cpp(24): warning C4273: 'vsomeip::runtime::get' : liaison DLL incohérente
1>F:\GIT\vsomeip\interface\compat/vsomeip/runtime.hpp(56): note: voir la définition précédente de 'get'
1>runtime_impl.cpp
1>Génération de code en cours...
1>   Création de la bibliothèque F:/GIT/vsomeip/build/RelWithDebInfo/vsomeip.lib et de l'objet F:/GIT/vsomeip/build/RelWithDebInfo/vsomeip.exp
1>application_impl.obj : warning LNK4217: symbole défini localement ?get@runtime@vsomeip@@SA?AV?$shared_ptr@Vruntime@vsomeip@@@std@@XZ (public: static class std::shared_ptr<class vsomeip::runtime> __cdecl vsomeip::runtime::get(void)) importé dans la fonction "public: virtual __thiscall vsomeip::application_impl::~application_impl(void)" (??1application_impl@vsomeip@@UAE@XZ)
1>runtime_impl.obj : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: virtual __thiscall vsomeip::runtime::~runtime(void)" (__imp_??1runtime@vsomeip@@UAE@XZ) référencé dans la fonction "public: virtual __thiscall vsomeip::runtime_impl::~runtime_impl(void)" (??1runtime_impl@vsomeip@@UAE@XZ)
1>runtime_impl.obj : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __thiscall vsomeip::runtime::runtime(void)" (__imp_??0runtime@vsomeip@@QAE@XZ) référencé dans la fonction "void __cdecl `dynamic initializer for 'private: static class std::shared_ptr<class vsomeip::runtime> vsomeip::runtime_impl::the_runtime_''(void)" (??__E?the_runtime_@runtime_impl@vsomeip@@0V?$shared_ptr@Vruntime@vsomeip@@@std@@A@@YAXXZ)
1>F:\GIT\vsomeip\build\RelWithDebInfo\vsomeip.dll : fatal error LNK1120: 2 externes non résolus
1>Génération du projet "vsomeip.vcxproj" terminée -- ÉCHEC.
========== Génération : 0 a réussi, 1 a échoué, 2 mis à jour, 0 a été ignoré ==========`

**Comment by lutzbichler** [comment]
Solved with 3.1.14.1
