### ISSUE TITLE
Not able to Fetech Servies information from json file in hello-World example

### ISSUE THREAD

**Issue by Himu-dev** [GENIVI/vsomeip#132]
Hi I try to run the hellow world example of vsomeip.
i refer the user guide to build the application. and it works,

but when i make the changes in .json file in services field. and build again the changes were not reflected changes i made 
orginal data:
"services":
    [
        {
            "service":"0x1111",
            "instance":"0x2222",
            "unreliable":"30509"
        }
    ],

my changes:
 "services":
    [
        {
            "service":"0xaaaa",
            "instance":"0xbbbb",
            "unreliable":"30509"
        }
    ],

please let me what changes is required so that ian resolve this issue.

**Comment by lutzbichler** [comment]
The .json has no impact on the build. You need to adapt the code if you want to use other service/instance identifiers.
