### ISSUE TITLE
EVENT calls : publish subscribe methodology queries

### ISSUE THREAD

**Issue by krishnaruby** [GENIVI/vsomeip#137]
I like to understand how  publish subscribe methodology works between server and client 

![image](https://user-images.githubusercontent.com/55469204/85927922-cf596880-b8c6-11ea-8693-18c3bd9620fe.png)

Once event occured at the server, server invokes notification call(publish)  to all intended subscribers(client). Is this a blocking or non blocking call ?  I  didn't find this information in vsomeIP user guide.  If this a non blocking call is there any configuration for number of dispatch thread for each server/client ?

**Comment by lutzbichler** [comment]
Messages are sent within the context of the io threads. Its number can be configured per application ("threads").

**Comment by krishnaruby** [comment]
Wats does the io thread mean ? Do u mean to say that dispatch threads will be created by vsomeip application and these dispatch threads will take care of notification to the appropriate client ?

**Comment by lutzbichler** [comment]
Yes, io threads are the threads that run the boost io context which handles the send and receive operations.

**Comment by krishnaruby** [comment]
Thanks for the information
