### ISSUE TITLE
Configuration module could not be loaded!

### ISSUE THREAD

**Issue by dotrung-dev** [GENIVI/vsomeip#139]
Hello all,

I try to run hello_world on Pi3+ armhf
so look like I can't load configuration file

```
 VSOMEIP_CONFIGURATION=helloworld-local.json VSOMEIP_APPLICATION_NAME=hello_world_service ./hello_world_service
Configuration module could not be loaded!
```
What's my failed ?

**Comment by lutzbichler** [comment]
This usually happens when the ld path does not contain the directory that contains libvsomeip3-cfg.so

**Comment by Stackleon** [comment]
Hi， 
I get simiarly error on Android platform. because of process dlopen the vsomeip-cfg.so name not corrspending with defined on internal_android.hpp.
You should be checked it on Pi3+ armhf.

**Comment by dotrung-dev** [comment]
I export LD_LIBRARY_PATH =/location build someip/ to solved it!
