### ISSUE TITLE
CommonAPI compatibility

### ISSUE THREAD

**Issue by FelixGail** [GENIVI/vsomeip#146]
Hello,

I was wondering if it is planned to update the CommonAPI bindings _([capicxx-someip-runtime](https://github.com/GENIVI/capicxx-someip-runtime) and [capicxx-someip-tools](https://github.com/GENIVI/capicxx-someip-tools))_  for this SomeIP implementation or if these projects have been abandoned.

If they have been abandoned, does an alternative solution to create stubs exist?

**Comment by lutzbichler** [comment]
CommonAPI is not abondoned. Version 3.2 will directly use the API of vSomeIP-Lib 3.

**Comment by FelixGail** [comment]
Thank you
