### ISSUE TITLE
examples with VSOMEIP_ENV_CONFIGURATION_MODULE doesn't work

### ISSUE THREAD

**Issue by mahaase** [GENIVI/vsomeip#153]
If I start the example apps with `VSOMEIP_ENV_CONFIGURATION_MODULE` set to json file, the apps will fail with: 

`Configuration module could not be loaded!`

**Comment by mahaase** [comment]
i guess i misunderstood something. my fault.

**Comment by eddiewangluminar** [comment]
@mahaase How did you solve this `Configuration module could not be loaded` issue? I got the same issue.
