### ISSUE TITLE
windows CreateFileW lck file

### ISSUE THREAD

**Issue by mahaase** [GENIVI/vsomeip#154]
https://github.com/GENIVI/vsomeip/blob/46e6856a1a61f4b24e29c1f2d3ed0b4ee7da0ede/implementation/utility/src/utility.cpp#L76

this line can lead to the following error:
`2020-07-18 09:32:42.275958 [error] vsomeip_v3::utility::is_routing_manager: CreateFileW failed: 50`
google said, error 50 means, that the file already exists.

if the application will be stopped manually, e.g. by debugger, this file will never be deleted.

for what is this lock?

will this also make problems, if the applications will be started on different systems?

**Comment by lutzbichler** [comment]
The lock is used to decide which applications becomes routing manager if this is not explicitely configured.
