### ISSUE TITLE
Is it possible for vsomeip2 app to communicate with vsomeip3 app

### ISSUE THREAD

**Issue by rlokanathan** [GENIVI/vsomeip#158]
Hi, currently, I am using common API to create my client app. My common API application uses vsomeip2. Whereas my service app is using vsomeip3 without common API. May I know are there any ways to make this communication successful?

Looking forward for reply.

**Comment by lutzbichler** [comment]
You must communicate using UDP/TCP and you must not use selective events. Local communication does not work. Please note that vSomeIP 3.x has a compatibility layer that enables it usage for application compiled to vSomeIP 2.x.

**Comment by rlokanathan** [comment]
Currently, I have been using TCP/UDP. My service is running in my Linux VM and my client app is running in windows host. Yet it doesnt work. However, once I replace both sides to vsomeip2 or vsomeip3 then it works fine.

**Comment by Arindom-2712** [comment]
I am also facing a similar issue. 
My client is  based on someip3 , running on Android.
Server is someip2 based running on linux.

Expecting a solution !
