### ISSUE TITLE
copy constructor function error

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#159]
group_(_other.group_) if this is error

![image](https://user-images.githubusercontent.com/32772277/95949967-530f7480-0e26-11eb-9638-a069504badc5.png)

should use deep copy???

**Comment by xiaostang** [comment]
### group_(other.group) if this is error???
![image](https://user-images.githubusercontent.com/32772277/95949597-94ebeb00-0e25-11eb-8e65-9d0a4a59d23e.png)

**Comment by lutzbichler** [comment]
Servicegroups are a leftover that are currently not used (therefore "group_" is always NULL).

**Comment by ByteXiaoTang** [comment]
> Servicegroups are a leftover that are currently not used (therefore "group_" is always NULL).

we may try to not leave a hole for later generations
