### ISSUE TITLE
Problem using 'clients' array.

### ISSUE THREAD

**Issue by dboscu** [GENIVI/vsomeip#160]
Client side ports limitation for unreliable conmmunication is not working.
Test was done using request_sample as a client application and response_sample as a server application using the default vsomeip.json between two ubuntu 18.04 VMs.
vsomeip.json snippet for clients array:
"clients" :
    [
        {
            "service" : "0x1234",
            "instance" : "0x5678",
            "unreliable_client_ports" : 
            {
                "first" : "31000",
                "last" : "31010"
            }
        }
	]
How should the clients array look like in order to succesfully limit client-side ports?

**Comment by lutzbichler** [comment]
"unreliable" : [ 31000, 31001, 31002, 31003, 31004, 31005, 31006, 31007, 31008, 31009, 31010 ]

instead of the "unreliable_client_ports" node
