### ISSUE TITLE
local_services_history

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#163]
### when one service has different instances, release will one instance, the whole service history will erase???
![image](https://user-images.githubusercontent.com/32772277/95949308-f790b700-0e24-11eb-86ee-e3455233f119.png)

**Comment by lutzbichler** [comment]
Fix planned for 3.1.19 / 3.2.0

**Comment by ByteXiaoTang** [comment]
here may also need change 
![image](https://user-images.githubusercontent.com/32772277/98807186-4007b880-2455-11eb-9f9b-7d5230a0485a.png)

**Comment by lutzbichler** [comment]
Fixed with v3.1.20.2
