### ISSUE TITLE
Check whether all additional bytes (if any) are excluded

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#164]
Check whether all additional bytes (if any) are excluded, ignore_.end() and i->second == 0xFF??? error
![image](https://user-images.githubusercontent.com/32772277/95962093-865aff00-0e38-11eb-8529-d61fa88a3d71.png)

**Comment by lutzbichler** [comment]
Fix planned for 3.1.19 / 3.2.0

**Comment by lutzbichler** [comment]
Fixed in v3.1.20.1

**Comment by ByteXiaoTang** [comment]
I can not find  the fix in v3.1.20.1 and v3.1.20.2
