### ISSUE TITLE
wireshark can't capature client log or log server send to client

### ISSUE THREAD

**Issue by leonliu1128** [GENIVI/vsomeip#165]
I run client and server script in one machine, with same ip address same as machine. Running is ok, then I use  the wireshark in side ubuntu to capture log, I find only server broadcasting log captured. Any one know why? Wirehshark don't support?

**Comment by fouzhe** [comment]
The internal communication in one machine is done via local endpoints which are implemented by unix domain sockets using the Boost. 
[The wiki](https://github.com/GENIVI/vsomeip/wiki/vsomeip-in-10-minutes#vsomeip-short-overview).
