### ISSUE TITLE
its_info->get_endpoint(!_reliable) ???why 

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#173]
### **why use !_reliable not _reliable here**

![image](https://user-images.githubusercontent.com/32772277/98624842-8b34a500-2349-11eb-8c61-6c8105c02be1.png)

**Comment by lutzbichler** [comment]
Because it must not be deleted if the other endpoint is still active.

**Comment by ByteXiaoTang** [comment]
> Because it must not be deleted if the other endpoint is still active.

thanks
i see
