### ISSUE TITLE
Thread unsafe

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#174]
### although the mutex has been used here. but when solve std::map<event_t, std::shared_ptr<event> > events，the unset_payload, clear_subscribers may still use the shared data， which the mutex may not protect

![image](https://user-images.githubusercontent.com/32772277/98650040-4f163a00-2373-11eb-92d2-3bd73f77b468.png)

**Comment by lutzbichler** [comment]
The mutex is for protecting "events_", not for protecting the within the events.

**Comment by ByteXiaoTang** [comment]
> The mutex is for protecting "events_", not for protecting the within the events.

### so how to make sure the thread safe when you solve the shared data in the map ??
