### ISSUE TITLE
the premise to solve event->add_ref question

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#175]
### the premise to solve event->add_ref question
in fact, _is_cache_placeholder is out in, but in the function, we may use set_cache_placeholder function and the event is_cache_placeholder may be different from the out in _is_cache_placeholder. 

![image](https://user-images.githubusercontent.com/32772277/98772332-7deae980-2421-11eb-8f31-eff85d99d67c.png)

**Comment by lutzbichler** [comment]
Fixed with v3.1.20.2
