### ISSUE TITLE
help me : i use vsomeip-3.1.16.1 and boost-1.70 by cross compiler，some compiler errors : 【error invalid use of auto】

### ISSUE THREAD

**Issue by liu8232303** [GENIVI/vsomeip#176]
vsomeip-3.1.16.1/implementationendpoints/src/server_endpoint_impl.cpp:724:47:error:invalid use of 'auto'
                       check_if_all_queues_are_empty();
i use cross compiler version gcc/g++ 4.93

**Comment by lutzbichler** [comment]
You could to try to replace "auto" in line 639 by "std::function<void ()>"
