### ISSUE TITLE
is_connected_ solve  error

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#182]
if _endpoint not equal sender_. 
then is_connected_  will be true. which may be an error, here may use a local variable  to replace is_connected_ , and if the variable  is false. set the is_connected_  false and do the other things..

![image](https://user-images.githubusercontent.com/32772277/100036197-baafdb00-2e3a-11eb-9631-e2a094976db7.png)

**Comment by lutzbichler** [comment]
Fixed with v3.1.20.2
