### ISSUE TITLE
How to build in MacOS[Query]

### ISSUE THREAD

**Issue by theetechy** [GENIVI/vsomeip#19]
Dear Authors,
Sorry to be noob !!!
I have been trying to build someip stack on macOS, i cannot complete cmake properly.
Could you please help me ... Attached is the Terminal Log

i have installed asciidoc, graphviz via brew
i have successfully compiled googletest

`Thees-iMac:build theetech$ cmake ..
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:564 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:903 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:1571 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:564 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:903 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:1571 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:564 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:903 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:1571 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindBoost.cmake:1956 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:83 (find_package)

-- Boost was not found!
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Systemd was not found, watchdog disabled!
Predefined unicast address: 127.0.0.1
Predefined diagnosis address: 0x00
Predefined routing application: vsomeipd
dot found
CMake Warning at CMakeLists.txt:354 (message):
  asciidoc is not installed.  Readme can not be built.

GTEST_ROOT is set. GTEST_ROOT = /Downloads/gtest1.7.0/googletest
CMake Error at CMakeLists.txt:425 (add_subdirectory):
  add_subdirectory given source "/Downloads/gtest1.7.0/googletest" which is
  not an existing directory.

CMake Warning at CMakeLists.txt:452 (message):
  TEST_IP_MASTER and/or TEST_IP_SLAVE isn't set.  Only local tests will be
  runnable Please specify them via for example -DTEST_IP_MASTER=10.0.3.1
  -DTEST_IP_SLAVE=10.0.3.125

CMake Warning at CMakeLists.txt:470 (message):
  TEST_UID and/or TEST_GID isn't set.  Security Tests are not runnable Please
  specify them for example -DTEST_UID=1000 -DTEST_GID=1000

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/daemon
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/tools
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/examples
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test
   used as include directory in directory /Users/theetech/Downloads/vsomeip/test

-- Configuring incomplete, errors occurred!
See also "/Users/theetech/Downloads/vsomeip/build/CMakeFiles/CMakeOutput.log".
Thees-iMac:build theetech$ 
`

**Comment by GenivivSOMEIPmaintainer** [comment]
MacOSX is unsupported. But from

Imported targets and dependency information not available for Boost version
(all versions older than 1.33)

it looks as if the problem is the available boost version being to old (the current version supports 1.54 until 1.64).
