### ISSUE TITLE
max_used_client_ids_index - misleading name

### ISSUE THREAD

**Issue by tolstoi911** [GENIVI/vsomeip#20]
Small one:
max_used_client_ids_index in struct configuration_data_t (internal.hpp) is a misleading name.
It is actually the count of used client ids, or the index of the next free client id, but not what it implies (the maximum index of used client IDs).

**Comment by GenivivSOMEIPmaintainer** [comment]
Agreed. Will be adapted in a future version (unlikely before vsomeip 3).
