### ISSUE TITLE
its_subscription

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#201]
error use of its_subscription when its_subscription is_selective
![image](https://user-images.githubusercontent.com/32772277/103191270-44a60480-490f-11eb-9bac-677fb6ae98c1.png)

**Comment by lutzbichler** [comment]
What do you think is the error? The overwriting at least is intentional.

**Comment by ByteXiaoTang** [comment]
> What do you think is the error? The overwriting at least is intentional.

why?

**Comment by ByteXiaoTang** [comment]
> What do you think is the error? The overwriting at least is intentional.

in fact , the  overwriting will not work

**Comment by lutzbichler** [comment]
We create a temporary object to handle the case of unsubscribing a single client from a selective event while others remain subscribed. Therefore we cannot use the original object as it would be removed during the unsubscription while being needed for holding the remaining clients.
