### ISSUE TITLE
its_data.entry and its.data.other 

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#203]
in file service_discovery_impl.cpp 
i can not understand the following code:
(867-870):
    if (its_entry && its_other) {
        its_data.entry_ = its_other;
        its_data.other_ = its_entry;
    }

**Comment by lutzbichler** [comment]
If both are set, its_entry contains a SUBSCRIBE and its_other a corresponding STOP SUBSCRIBE. In this case we must swap ensure the STOP SUBSCRIBE entry comes first and therefore swap them.
