### ISSUE TITLE
what is the usage of Counter in EventGroup entries

### ISSUE THREAD

**Issue by ByteXiaoTang** [GENIVI/vsomeip#211]
![image](https://user-images.githubusercontent.com/32772277/104260549-b1e49880-54be-11eb-83ba-edeed778c141.png)
when in vsomeip coding,
we just serialize like the following code, i may not understand.
![image](https://user-images.githubusercontent.com/32772277/104260601-cc1e7680-54be-11eb-9e74-2b8508d6a051.png)

**Comment by lutzbichler** [comment]
The specification states that "Counter" may be used to differentiate identical SubscribeEventgroups and shall be set to 0 if not being used. We do not use it.
