### ISSUE TITLE
Communication between two devices

### ISSUE THREAD

**Issue by robin-gt** [GENIVI/vsomeip#22]
Hej there,

i followed the [vsomeip in 10 minutes](https://github.com/GENIVI/vsomeip/wiki/vsomeip-in-10-minutes#devices) tutorial, but can't get any communication between two devices (skipped step [_Subscribe/Notify_](https://github.com/GENIVI/vsomeip/wiki/vsomeip-in-10-minutes#subscribe--notify) ). I tried two Raspberry Pi 3 as well as two virtual machines (Xubuntu 16.04 and Ubuntu 16.04). Though internal (on one device) communication works, also when using a *config.json*. 

I copied the given examples. Changed the routing manager in the *client-config.json* to ```World``` (the name of the service application, which should be responsible for routing - imho)
When using 'local' or the network devices __own__ IP address for unicasting, a payload is transmitted.
Tcpdump or Wireshark show nothing except for the *service discovery* multicasts.

When running the service on a different device (vm) the client reports:
> [warning] local_client_endpoint::connect: Couldn't connect to: /tmp/vsomeip-0 (No such file or directory / 2)

Well, indeed the socket ```/tmp/vsomeip-0``` is on a different device in it's /tmp directory.

How can i get this working? Any further information required?

Regards,
Robin

**Comment by robin-gt** [comment]
Okay, obviously my routing manager isn't configured correctly. I wont use the _unix domain socket_, but the TCP-Endpoint.
I'm crawling the *user guide* as well as the vsomeip-master/config/* . 
I guess i *mis*configured the *vsomeip-conf.json*, using the examples.
What needs to be done/read to overcome errors like: 
```
[error] Routing info for remote service could not be found! (1343): [1234.5678.0421] 0001
[info] init_routing_endpoint Routing endpoint at /tmp/vsomeip-0
```
Help or hints are much appreciated.

**Comment by robin-gt** [comment]
okay nvm,
was a misconfigured VM Network.

**Comment by sachindes** [comment]
robin-gt
Can you please share your detailed solution?
I am too getting same issue: /tmp/vsomeip-0 at client side
