### ISSUE TITLE
Questions about TLV support

### ISSUE THREAD

**Issue by nhkim1104** [GENIVI/vsomeip#23]
Hello,

Does vsomeip support a TLV(Type-Length-Value) encoding scheme? 
If not, is there a support plan?

**Comment by GenivivSOMEIPmaintainer** [comment]
Please explain in greater detail what this is about.

**Comment by nhkim1104** [comment]
Hello, 

TLV (type-length-value or tag-length-value) is a kind of data encoding scheme.
For simple example;
- type = AE 01 0A
- length = 04
- value = 12 34 00 56  
If we want to send  data we can make it like (AE 01 0A 04 12 34 00 56).

For more detailed information please refer to wiki page below. I think it is better to see wiki than I explain it.
=> https://en.wikipedia.org/wiki/Type-length-value

Thanks

**Comment by GenivivSOMEIPmaintainer** [comment]
The SOME/IP protocol does not support TLV. If you need extensible data structures, you can use unions and/or extensible structs. Please note that vsomeip does not handle the message payload, this is done by [CommonAPI-SomeIP](https://github.com/GENIVI/capicxx-someip-runtime).

**Comment by nhkim1104** [comment]
Thanks for your response. As you commented, I will refer the CommonAPI-SomeIP.
