### ISSUE TITLE
Interface for set_protocol_version not found

### ISSUE THREAD

**Issue by Wided-Fth** [GENIVI/vsomeip#232]
Hello, 
I can not find an interface for setting the protocol version.  ( I need it for some use cases)

 "vsomeip/interface/vsomeip/message_base.hpp" does not contain the "set_protocol_version( )" method 
 
 Is it misssing or am I  doing things wrong ?
 
 My expectation of code : 
 std::shared_ptr< vsomeip::message > request;
 request = vsomeip::runtime::get()->create_request();
request->set_protocol_version ( 0xFF );

Thanks in advance.

**Comment by lutzbichler** [comment]
This is the version of the SOME/IP protocol and (at least as we know) there is only version 1.
