### ISSUE TITLE
Porting VSomeip3 to QNX

### ISSUE THREAD

**Issue by liutiegang** [GENIVI/vsomeip#236]
There is a requirement for VSomeip3 to run on QNX. I can find QNX VSomeip2 on https://github.com/bonewell/vsomeip.
But VSomeip3 changed too much code, porting it is a bit difficult.
Does anyone have successful experience on porting VSomeip3 to QNX?

Any help would be greatly appreciated.

Thank you,
Liutiegang

**Comment by Joghurt** [comment]
https://github.com/lixiaolia/vsomeip-qnx looks promising
