### ISSUE TITLE
The interval between two messages

### ISSUE THREAD

**Issue by yooouxin** [GENIVI/vsomeip#250]
I find that there has a interval between two messages,even if there is no delay between two transmissions.
I write a very sample code for test latency,application will send a message continuously,but in fact,it has a interval between two messages about 2ms
![image](https://user-images.githubusercontent.com/58878356/118392298-84c21580-b66b-11eb-8979-d1ff31af02ec.png)
![image](https://user-images.githubusercontent.com/58878356/118392462-76c0c480-b66c-11eb-895e-16c330153823.png)

But when I insert a delay between transmissions,it comes ok.When I send a message in a 100ms cycle, the result of grabbing the packet is also 100ms.

I want to know why this happened.
Thanks

**Comment by ByteXiaoTang** [comment]
Wireshark本身带刷新采集周期

**Comment by yooouxin** [comment]
> Wireshark本身带刷新采集周期

并不是这个原因，裸boost库或socket是不会到2ms这个级别的，应该是vsomeip底层的一些算法，可能带个buffer之类的

**Comment by ByteXiaoTang** [comment]
![IMG_20210517_103111.jpg](https://user-images.githubusercontent.com/32772277/118425360-a10d9300-b6fb-11eb-9442-4d16a53f94d0.jpg)

此处，愿意是判空，结果is_debounce和its_retention值为默认2ms.防抖debounce用了起来，就是你看到的2ms
