### ISSUE TITLE
$ ./service-example   Configuration module could not be loaded!

### ISSUE THREAD

**Issue by Miaoishappening** [GENIVI/vsomeip#253]
hi everyone,
i was following the instruction "vsomeip in 10 minutes"
here is what i have done:

```
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/ ..
$ make 
$ make install
```
no error so far

and i want to try first "service-example.cpp"
in new service-example folder with following codes: 
```
#this is service-example.cpp
#include <vsomeip/vsomeip.hpp>

std::shared_ptr< vsomeip::application > app;

int main(){
    app = vsomeip::runtime::get()->create_application("World");
    app->init();
    app->start();
}
```
```
#this is CMakeLists.txt
cmake_minimum_required (VERSION 3.19.8)
#project(MyProject VERSION 1.0.0)
set (CMAKE_CXX_FLAGS "-g -std=c++0x")

find_package (vsomeip3 REQUIRED)
find_package( Boost 1.55 COMPONENTS system thread log REQUIRED )

include_directories (
    ${Boost_INCLUDE_DIR}
    ${VSOMEIP_INCLUDE_DIRS}
)

add_executable(service-example service-example.cpp)
target_link_libraries(service-example vsomeip3 ${Boost_LIBRARIES})


```
Then i did this:
```
$ mkdir build
$ cd build
$ cmake ..
$ make
[ 50%] Linking CXX executable service-example
[100%] Built target service-example
$ ./service-example 
Configuration module could not be loaded!

```

so my service-example did not work...
can someone help me with this one?

**Comment by ByteXiaoTang** [comment]
配置文件和环境变量加载了么！

**Comment by Miaoishappening** [comment]
> 配置文件和环境变量加载了么！

还要配置文件和环境变量嘛?这个10分钟的介绍里面也没有诶。。。
请问一下这个怎么配置呢?能不能详细一些。

**Comment by ByteXiaoTang** [comment]
具体可参考readme

**Comment by Miaoishappening** [comment]
> 具体可参考readme

谢谢问题已经解决了. :D

**Comment by Miaoishappening** [comment]
Solution: 
You should build vsomeip like this:

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/ ..
$ cmake -DENABLE_SIGNAL_HANDLING=1 .. //added line
$ make 
$ make install
```

**Comment by oska874** [comment]
> > 具体可参考readme
> 
> 谢谢问题已经解决了. :D

你是怎么解决的？我按照readme的流程，make&install，但是运行hello_world_service 还是会报相同的错误。

**Comment by Miaoishappening** [comment]
> > > 具体可参考readme
> > 
> > 
> > 谢谢问题已经解决了. :D
> 
> 你是怎么解决的？我按照readme的流程，make&install，但是运行hello_world_service 还是会报相同的错误。

通过上面我的solution的步骤走还是不可以嘛？

**Comment by Daniel-li121** [comment]
> > > > 具体可参考readme
> > > 
> > > 
> > > 谢谢问题已经解决了. :D
> > 
> > 
> > 你是怎么解决的？我按照readme的流程，make&install，但是运行hello_world_service 还是会报相同的错误。
> 
> 通过上面我的solution的步骤走还是不可以嘛？

after those steps you mentioned, refresh the cache configuration with command:
`sudo ldconfig`

**Comment by SomnathHolkar** [comment]
I am also facing same issue.
I followed the exact steps mentioned as below.

$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/ ..
$ cmake -DENABLE_SIGNAL_HANDLING=1 .. //added line
$ make 
$ make install

**Comment by eddiewangluminar** [comment]
@SomnathHolkar According to [Issue 139](https://github.com/COVESA/vsomeip/issues/139) it's because `libvsomeip3-cfg.so` couldn't be found. It can be solved by adding this prebuild library's path to `LD_LIBRARY_PATH`.

**Comment by semajz** [comment]
“sudo ldconfig” worked~
