### ISSUE TITLE
Communicate between 2 PC

### ISSUE THREAD

**Issue by peti634** [GENIVI/vsomeip#257]
Hi,

I want to run a hello world example, for test the communicate between 2 PC.
I see this message in log always:
`Client [1] is connecting to [102] at /tmp/vsomeip-...`
I think it is not correct, it will not able to communicate on netwrok (TCP), because it is just file IPC.
Tested on all predfined cofing file.

**Comment by leonliu2811** [comment]
I also fail to communicate between 2 pc. How to resolve?

**Comment by lutzbichler** [comment]
You need to adapt the sample configuration(s) to your network settings.
