### ISSUE TITLE
Multiple Subscriptions for the same Cyclic Event

### ISSUE THREAD

**Issue by rags92** [GENIVI/vsomeip#260]
I have two VM's communicating with each  other using  SOME/IP-TP on a UDP Port.  It is a cyclic event communication in intervals of 50ms with a payload of 4k bytes being transferred from server to client. The communication works fine, however in the wireshark trace, i see multiple subscriptions for the same event i.e. the offer and subscription pairs occurs at regular intervals. 
Is this normal behavior. From the autosar specification, I assumed that the subscription occurs only once and the events are sent cyclically forever. 
Could someone comment on this publish-subscribe behavior. I have attached the trace for the reference. Also adding the screenshot.
[wireshark trace.zip](https://github.com/GENIVI/vsomeip/files/6729394/wireshark.trace.zip)
<img width="943" alt="trace snap" src="https://user-images.githubusercontent.com/86628996/123707458-095aa300-d86a-11eb-9269-8e91f37f1eb6.PNG">

**Comment by Almeida-Oco** [comment]
That is indeed expected behavior which is also foreseen in the SOME/IP Service Discovery AUTOSAR specification in PRS_SOMEIPSD_00449. 

What you're referring to is kind of a "special" case that, as far as I know, the client part of vsomeip does not implement.
