### ISSUE TITLE
No usage examples and configuration files for e2e protected 

### ISSUE THREAD

**Issue by 007herelsp** [GENIVI/vsomeip#27]
I tried to use the E2E protection feature, but I didn't find the relevant usage examples and configuration files, which caused me to not use the feature

**Comment by JaehoonLeee** [comment]
I also tried to use the e2e protection. But, e2e protection feature is difficult to use.
Please , share example configuration to us ?

**Comment by gunnarx** [comment]
@GenivivSOMEIPmaintainer Please answer the ticket.

**Comment by lutzbichler** [comment]
Please take a look into test/e2e_tests/conf. It contains examples of howto configure messages to be protected/checked.

**Comment by GHARBIAchref** [comment]
Hello @fengmao31  @duartenfonseca  
 I want to use end-to-end protection in my application. Is using end-to-end protection done solely through configuration in .json configuration files on both the client and server sides of the services, or does it also require code implementation within my algorithm? And how can I verify if the E2E protection profile 4 is working correctly in Wireshark? 
 thanks

**Comment by fengmao31** [comment]
> Hello @lutzbichler I want to use end-to-end protection in my application. Is using end-to-end protection done solely through configuration in .json configuration files on both the client and server sides of the services, or does it also require code implementation within my algorithm? And how can I verify if the E2E protection profile 4 is working correctly in Wireshark? thanks

You donnot need code with your algorithm. Mostly adas standards vsomeip finish for you, just config it.

**Comment by fengmao31** [comment]
You can see the byte in the network package. And you can caculate the e2e part in the header. Of course, if you have autosar tool, it will be more easy for you. The tool can show the structure of the message.
