### ISSUE TITLE
Why can't you subscribe to eventgroups through SD multicast ?

### ISSUE THREAD

**Issue by yunfeiyangcc** [GENIVI/vsomeip#270]
Why can't you subscribe to eventgroups through SD multicast ?

![image](https://user-images.githubusercontent.com/8465050/126755751-d75b9a59-f86b-406e-85c5-49acfe36f11a.png)

TC8 document CASE: SOMEIP_ETS_093: SD_Check_Reboot_Detection_separate_multicast_and_unicast

This case requires sending subscriptions through both multicast and unicast, but returns the NACK in the code.

![image](https://user-images.githubusercontent.com/8465050/126756324-cccd6f1f-bc23-4d6f-95e5-d18d504e27bf.png)

**Comment by lutzbichler** [comment]
FindService messages are sent by multicast (as the device does not know the service location) and are answered by unicast or multicast (dependent on the time they are received). Subscriptions are sent to the device that offers the service that provides the eventgroup.
