### ISSUE TITLE
Header in Wireshark

### ISSUE THREAD

**Issue by tobsenthomas2** [GENIVI/vsomeip#279]
Hi and thx for the great work!
I don't get the mean of a  few Bytes in my Wireshark trace.
![image](https://user-images.githubusercontent.com/55584250/131847736-c21e7445-d357-4050-af20-52aa548f9ccf.png)

I dont know what the Bytes in the circle should stand for. Can someone help? (maybe there is also a docu i didn't find?)
Where the first 02 stands it is incrementing after each frame. Is there anywhere a config where i can "switch them off"?

**Comment by tobsenthomas2** [comment]
Maybe as additional Info:
12 43 80 01 Message ID
00 00 02 40 Length
**00 00 00 02 01 00 02 00 unknown**
12 55 00 03 RequestID
01 00 00 00 Protocol Version, IV, MT and Return Code

**Comment by ziyangfu** [comment]
Hi， can you using wireshark to parse the someip header？
I can not do it like following image.
wireshark version ： 3.6
![9](https://user-images.githubusercontent.com/52022474/147535761-0e5a64e6-964a-444d-a395-629dde165890.png)
