### ISSUE TITLE
TCP example and large data with UDP

### ISSUE THREAD

**Issue by myih** [GENIVI/vsomeip#28]
Hi

I'm trying to transfer data between devices, so far I can only transfer small data (<1400B) with UDP. Autosar's specification mentioned someip should be able to transfer large data with "Segmentation functionality (SOME/IP-TP)", but I have no idea how to use it.

As for TCP, I can't even get the request/response examples working. (The subscribe/notification examples seem to work) The service and client were connected, but when the client tries to send request, the following error occur: 
`[error] Routing info for remote service could not be found! (1343): [1234.5678.0421] 0001
`

I tried modify some settings in the json file with no luck. 
I'm new to this, any help would be appreciated!

**Comment by hemalbavishi** [comment]
Hello,

You need to pass --tcp command line option while executing request_sample application to transfer data over TCP. I tested with latest version and it seems to be working. 

As far as I know, SOME/IP-TP is not implemented as part of vSomeIP so you won't be able to transfer large data over UDP. 

Cheers!
