### ISSUE TITLE
Project does not build on Windows 

### ISSUE THREAD

**Issue by ioptest** [GENIVI/vsomeip#34]
I did what is written in [https://docs.microsoft.com/en-us/cpp/vcpkg](url) and managed to get a .sln but the code has errors.  
Is it possible someone to provide the way to build vsomeip for Windows?

First error is
Error	C1083	Cannot open include file: 'boost/asio/detail/addressof.hpp': No such file or directory	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_ext.hpp	29	

'boost/asio/detail/addressof.hpp' such a file does not exist in the latest boost package(boost_1_67_0.7z). I removed the include for it. 

After this a lot of new errors:
Severity	Code	Description	Project	File	Line	Suppression State

Error	C2660	'boost::asio::detail::socket_ops::poll_write': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	195	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	38	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "bind"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	41	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	48	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	55	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	60	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "native"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	65	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "is_open"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	89	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "shutdown"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	91	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "shutdown_both"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	91	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "close"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	92	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "is_open"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	99	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	182	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "reuse_address"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	182	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	183	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	186	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	195	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "reuse_address"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	195	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	196	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	199	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	238	

Error (active)	E0135	class "boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp, boost::asio::datagram_socket_service_ext<boost::asio::ip::udp>>" has no member "set_option"	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	242	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\impl\socket_ops_ext.ipp	141	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvfrom_op_ext.hpp	94	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recv_op_ext.hpp	85	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvmsg_op_ext.hpp	86	

Error	C2660	'boost::asio::detail::socket_ops::poll_write': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	195	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	266	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	347	

Error	C2977	'boost::asio::basic_socket': too many template arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	47	

Error	C2955	'boost::asio::basic_socket': use of class template requires template argument list	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	48	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\impl\socket_ops_ext.ipp	141	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvfrom_op_ext.hpp	94	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recv_op_ext.hpp	85	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvmsg_op_ext.hpp	86	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	266	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	347	

Error	C2977	'boost::asio::basic_socket': too many template arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	47	

Error	C2955	'boost::asio::basic_socket': use of class template requires template argument list	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	48	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\impl\socket_ops_ext.ipp	141	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvfrom_op_ext.hpp	94	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recv_op_ext.hpp	85	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvmsg_op_ext.hpp	86	

Error	C2660	'boost::asio::detail::socket_ops::poll_write': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	195	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	266	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	347	

Error	C2977	'boost::asio::basic_socket': too many template arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	47	

Error	C2955	'boost::asio::basic_socket': use of class template requires template argument list	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	48	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	38	

Error	C2039	'bind': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	41	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	48	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	55	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	60	

Error	C2039	'native': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	65	

Error	C2039	'is_open': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	89	

Error	C2039	'shutdown': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	91	

Error	C2039	'shutdown_both': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	91	

Error	C2065	'shutdown_both': undeclared identifier	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	91	

Error	C2039	'close': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	92	

Error	C2039	'is_open': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	99	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	182	

Error	C2039	'__this': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	182	

Error	C2039	'reuse_address': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	182	

Error	C3861	'reuse_address': identifier not found	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	182	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	183	

Error	C2039	'__this': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	183	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	186	

Error	C2039	'__this': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	186	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	195	

Error	C2039	'__this': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	195	

Error	C2039	'reuse_address': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	195	

Error	C3861	'reuse_address': identifier not found	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	195	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	196	

Error	C2039	'__this': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	196	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	199	

Error	C2039	'__this': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	199	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	238	

Error	C2039	'set_option': is not a member of 'boost::asio::basic_datagram_socket_ext<boost::asio::ip::udp,boost::asio::datagram_socket_service_ext<Protocol>>'	vsomeip	\vsomeip-2.10.21\implementation\endpoints\src\udp_server_endpoint_impl.cpp	242	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\impl\socket_ops_ext.ipp	141	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvfrom_op_ext.hpp	94	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recv_op_ext.hpp	85	

Error	C2061	syntax error: identifier 'io_service_impl'	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_recvmsg_op_ext.hpp	86	

Error	C2660	'boost::asio::detail::socket_ops::poll_write': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	195	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	266	

Error	C2660	'boost::asio::detail::socket_ops::poll_read': function does not take 3 arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\detail\reactive_socket_service_base_ext.hpp	347	

Error	C2977	'boost::asio::basic_socket': too many template arguments	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	47	

Error	C2955	'boost::asio::basic_socket': use of class template requires template argument list	vsomeip	\vsomeip-2.10.21\implementation\helper\boost\asio\basic_datagram_socket_ext.hpp	48

**Comment by PeiLinCN** [comment]
I think the error is based on boost version dependency with vsomeip codes, the boost 1.6 would be fine for compiling the vsomeip and using this boost version wouldn’t happen your first error.

Thanks,
-Lin

**Comment by ioptest** [comment]
All the errors are gone with using boost 1.60. Thanks for referring to this version. I wouldn't think of trying it without that suggestion.
