### ISSUE TITLE
Service crashes on port scan

### ISSUE THREAD

**Issue by ioptest** [GENIVI/vsomeip#37]
I am using vsomeip on Windows 7 with boost_1_65_1 and it works but I tride https://www.advanced-port-scanner.com/ to scan TCP port 51234 and the service crashed with error "vector subscript out of range". My guess is that in \vsomeip-2.10.21\implementation\endpoints\src\local_server_endpoint_impl.cpp line 323 the index used is out of range.

**Comment by gunnarx** [comment]
@GenivivSOMEIPmaintainer please reply to the ticket!

**Comment by lutzbichler** [comment]
This area has been reworked for vSomeIP v3.
