### ISSUE TITLE
vsomeip error "libvsomeip-cfg.so.2 "

### ISSUE THREAD

**Issue by Azsxzsxa** [GENIVI/vsomeip#38]
I try to run the "first application" from the vsomeip git hub page and I get the following error when i do ./service-example : 

[0x00007f2275b62740] [error]   Loading failed: (libvsomeip-cfg.so.2: cannot open shared object file: No such file or directory)
Service Discovery module could not be loaded!

 I'm running it on a VM

**Comment by Azsxzsxa** [comment]
i did sudo make install and it didnt appear anymore, thanks tho :)

**Comment by bit2shift** [comment]
@Azsxzsxa congratulations, you just polluted your system when there was no need to. Good luck cleaning that mess without a full system reinstall. /s
Assuming you built vsomeip locally, ˋLD_LIBRARY_PATH=<vsomeip-path>/build ./service-exampleˋ is what was suggested. No need to taint your system with stuff you might end up forgetting about in the following weeks.
