### ISSUE TITLE
Availability handler is called only once

### ISSUE THREAD

**Issue by cmm1981** [GENIVI/vsomeip#46]
Hello,

I want to write functions on a Raspberry Pi for testing a real ECU. But my first try doesn't work, because the availability handler is only called once at application start. Each change is logged on stderr but there is no output on stdout:

![image](https://user-images.githubusercontent.com/8583445/52569270-14374900-2e11-11e9-8c1d-5dd37776748a.png)

The application looks currently similar to the example like this:
![image](https://user-images.githubusercontent.com/8583445/52569408-6aa48780-2e11-11e9-82e0-f4ffcf30a377.png)

Best regards,
Conny

**Comment by lutzbichler** [comment]
Your request_service call uses the default version which is 0.0. You need to change it to:

app->request_service(SERVICE_ID, INSTANCE_ID, 1, 0)
