### ISSUE TITLE
Subscription_status_handler not called

### ISSUE THREAD

**Issue by anmCML** [GENIVI/vsomeip#47]
Hello,

I have the following problem:
A service is offered on the ServiceProvider side. Accordingly, a subscription_status_handler is registered here (register_subscription_status_handler(...)) in order to be aware when a client is subscribed to a specific event group.

On the client side subscribe(...) is called accordingly.

In both cases I can't see an error from the logs. Nevertheless, the subscription_status_handler is never called, although I can see in the log that the subscribe() call is confirmed with a SUBSCRIBE ACK.

If I use a subscription_handler (register_subscription_handler) it is called every time a client subscribed, but unfortunately I don't know which event group it is.

Is there anything else to note here? 

PS: The service-discovery is activated.

I hope somebody can help me.
Thank you in advance.

**Comment by lutzbichler** [comment]
The subscription_status_handler is a called on client side to indicate whether or not a server has acknowleded the subscription or not.

The subscription handler is called on service side whenever a client subscribes or unsubscribes. If you need to know the eventgroup, you need to register a specific handler for the eventgroup.
