### ISSUE TITLE
ARM build support  documents?

### ISSUE THREAD

**Issue by kumarasamy** [GENIVI/vsomeip#5]
Hello ,

Please guide me how to build the vsomeip for ARM boards ?

**Comment by GenivivSOMEIPmaintainer** [comment]
Building of vsomeip is documented in the vsomeip user guide. If you have a build environment with cmake and boost, building should work the same way it does on other platforms.

**Comment by kumarasamy** [comment]
Thanks for your reply.But i am trying to port this to android platform for that reason i asked this question.

**Comment by gunnarx** [comment]
Link to user guide please?  It's not in the README.

**Comment by gunnarx** [comment]
Thanks.  (Can the issue be closed now?)

**Comment by GenivivSOMEIPmaintainer** [comment]
@kumarasamy: This sound more like a problem with the cross(=) build environment. The cmake you use for building the ARM target should not find host components.
