### ISSUE TITLE
Unable to build on OSX High Sierra

### ISSUE THREAD

**Issue by terrisgit** [GENIVI/vsomeip#51]
cmake runs fine but when I run make, I get:

[  1%] Building CXX object CMakeFiles/vsomeip.dir/implementation/endpoints/src/client_endpoint_impl.cpp.o
In file included from <built-in>:357:
<command line>:4:9: error: macro name must be an identifier
#define -DBOOST_LOG_DYN_LINK 1

cmake and gcc versions:

cmake version 3.14.4
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by terrisgit** [comment]
Ah. OSX is not supported.

**Comment by cfanatic** [comment]
You can run vsomeip in a docker container, though. Take a look at https://github.com/cfanatic/vsomeip-fuzzing for reference.
