### ISSUE TITLE
Does vsomeip have plans to support Android?

### ISSUE THREAD

**Issue by AnaBit** [GENIVI/vsomeip#55]
I want to import vsomeip into the android system, but I have encountered many problems, such as shared memory functions are not supported. Does vsomeip have plans to support android system?

**Comment by gunnarx** [comment]
Yes, this is an interesting question for many companies, and investigations are ongoing.  If you start trying it, please share your experiences (with more detail).  Do you get a compilation error for the shared memory functions?

**Comment by AnaBit** [comment]
Yes, I have encountered two problems, one is shared memory, one is std::dynamic_pointer_cast The return value is NULL, this should be a problem with NDK. https://github.com/android-ndk/ndk/issues/533; https://github.com/android-ndk/ndk/issues/519

**Comment by gunnarx** [comment]
Thanks for your input @AnaBit.
GENIVI alliance is running a special-interest-group (SIG) for automotive companies that are working with Android.  I think it's likely that we use that group to try to synchronize different initiatives around the ability to use SOME-IP in systems that also include an Android ECU.  And I think that would start relatively soon.   Hopefully you can participate in this discussion.

**Comment by lutzbichler** [comment]
Android support is planned for vsomeip 3.

**Comment by AnaBit** [comment]
When is the plan to release vsomeip3.0?

**Comment by lutzbichler** [comment]
It is planned to be released until end of this month.

**Comment by AnaBit** [comment]
Thank you

**Comment by zhyh2010** [comment]
Excuse me, it's mentioned that vsomeip3 should support android ECU at the end of 2019.7.30 , where can I find it?

**Comment by zeerd** [comment]
it there any news for this v3?

**Comment by zeerd** [comment]
@gunnarx  I am interesting in this SIGN, any way to join it?

**Comment by kornava** [comment]
any updates?

**Comment by nkh-lab** [comment]
Now vsomeip supports both AOSP and NDK builds, here is examples:
https://github.com/GENIVI/vsomeip/blob/master/examples/hello_world/readme_android
