### ISSUE TITLE
vsomeip communication between docker containers on linux

### ISSUE THREAD

**Issue by Prasad454** [GENIVI/vsomeip#58]
Hello,

I have created 2 docker containers as below:
![image](https://user-images.githubusercontent.com/53291749/61852763-cf99f880-aeec-11e9-8de0-4d4c0ba9a5aa.png)

And i am able to communicate between two applications using vsomeip as mentioned in the vsomeip example.

But i want communicate with vsomeip between the two containers, i explored through online but i dont find any useful info.

I am very new to linux platform.

Kindly help me in providing the possibilities for my requirement.

**Comment by AnaBit** [comment]
Are the IP addresses of two dockers in the same network segment?

**Comment by lutzbichler** [comment]
In general communication between (docker) containers is no different from communication between regular devices. Thus, you can use the configuration examples from the config directory (adapting the IP addresses configured as "unicast" parameter and setting the multicast route should be all that is necessary). For any more target oriented help please provide more detailed information about your configuration, what you are trying to do/achieve and what is going wrong.
