### ISSUE TITLE
SOME/IP-TP Support in vsomeip 3.0?

### ISSUE THREAD

**Issue by adaschmac** [GENIVI/vsomeip#60]
Hello,

Will the next release of vsomeip include built-in support for [SOME/IP Transport Protocol](https://www.autosar.org/fileadmin/user_upload/standards/classic/4-3/AUTOSAR_SWS_SOMEIPTransportProtocol.pdf)?

Thanks,
Adam

**Comment by lutzbichler** [comment]
It will.
