### ISSUE TITLE
Build process failed on linux mint and ubuntu due to boost::log error

### ISSUE THREAD

**Issue by LamdaLamdaLamda** [GENIVI/vsomeip#63]
Build process fails at **[100%] Linking CXX executable vsomeipd**. Throws the following error: **CMakeFiles/vsomeipd.dir/vsomeipd.cpp.o: In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<vsomeipd_process(bool)::{lambda()#1}> > >::_M_run()':
/usr/local/include/boost/log/sources/basic_logger.hpp:456: undefined reference to `boost::log::v2_mt_posix::core::get_logging_enabled() const' ...**

Boost 1.65 is currently installed but on 1.55 the same error was thrown. Boost itself is perfectly functional. I´ve tested it on Ubuntu and also Mint. None of it worked properly (same error was thrown). A few month ago the vsomeIP worked properly on Ubuntu. Maybe someone has an idea?

**Comment by lutzbichler** [comment]
Which ubuntu version are you using and what is the output of "apt list --installed | grep boost" ?

**Comment by ilyashamd** [comment]
@LamdaLamdaLamda Did you figure a solution? I am having the same issue.

**Comment by lutzbichler** [comment]
boost::log is no longer used.
