### ISSUE TITLE
Is optional message like REQUEST_ACK is implemented in vsomip stack

### ISSUE THREAD

**Issue by arcsweety** [GENIVI/vsomeip#67]
Hi,

I have come across an observation that for vsomeip REQUEST message, there is no REQUEST_ACK is  sent. As I understand that REQUEST_ACK is an optional message. I either get a response or notification. But never received REQUEST_ACK.

So my understanding is that, it is currently not implemented in the vsomeip code. Is my understanding correct? Please confirm.

Many Thanks!

Archana

**Comment by lutzbichler** [comment]
You are right, REQUEST ACK is not implemented.
