### ISSUE TITLE
Order of events vs eventgroups in config matters

### ISSUE THREAD

**Issue by jhershbe** [GENIVI/vsomeip#68]
`void configuration_impl::load_eventgroup() {
  ...
                      else {
                            its_event = std::make_shared<event>(its_event_id,
                            false, false);
                 }
...
`
This code inserts a dummy event with the wrong is_field and is_reliable entries, causing the actual settings to not be stored. When the actual event is loaded, it is treated as a duplicate. JSON is an unordered data format. so this is broken.

**Comment by lutzbichler** [comment]
Fixed with v3.1.20.2
