### ISSUE TITLE
vsomeip sends offer service mesage more than repetitions_max value

### ISSUE THREAD

**Issue by arcsweety** [GENIVI/vsomeip#69]
Hi,
In repetition phase, Vsomeip sends offer service message more than the repetition_max value.
If repetition_max is defined as 5. Offer service is sent 6 times.
As per the Autosar document, it should be sent 5 times.
Is there any reason behind this?

Regards,
Archana

**Comment by tjpsantiago** [comment]
Hi arcsweety,

I am not part of Genivi but I think the first offer service message is not counted as a repetition that is why offer service is sent repetition_max + 1 times always.

I am not sure about the Autosar document but the config element name makes sense.
