### ISSUE TITLE
What is usage of shm in somip / If possible to use some other IPC other than sharedmemory ?

### ISSUE THREAD

**Issue by kumarasamy** [GENIVI/vsomeip#7]
I am trying to port someip  code to android platform. In android shared memory support was not there . Kindly guide me, if possible to use the file instead of shared memory. kindly share your view reg this usage in implementation/utility/src/utility.cpp.

**Comment by GenivivSOMEIPmaintainer** [comment]
The access to the shared memory (or its replacement) must be serialized as it is used by different applications (or the startup of the applications must be serialized). Alternatively, all applications can be configured with in the configuration file.
