### ISSUE TITLE
Documentation error - stated supported boost version not correct

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/vsomeip#72]
"vsomeip uses Boost >= 1.55:" is not correct. I tested with 1.69 which does not work. The docs thus should read "vsomeip uses Boost  >=1.55 and <1.69:" (or similar, depending on compatibility of in-between versions)
See
https://github.com/GENIVI/vsomeip/issues/18
https://github.com/GENIVI/vsomeip/issues/31
https://github.com/GENIVI/vsomeip/issues/52
for more information and patches.

**Comment by lutzbichler** [comment]
CMakeFile now checks for the supported versions of boost.
