### ISSUE TITLE
A lot of fixes planned for v3, but where can I find the dev branch for v3?

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/vsomeip#76]
@GenivivSOMEIPmaintainer   @lutzbichler Is there an ETA for v3? A lot of fixes seem to be delayed until then...
Does the v3 dev branch live in a separate repository?

**Comment by TheDraguun** [comment]
This could be interesting if looking for alternatives:
https://github.com/doz21/vsomeip/branches
https://github.com/jacky309/someip

**Comment by ManuelKugelmann** [comment]
Ok,@lutzbichler, so v3 is finally here. But it still feels like the project lives elsewhere ...

**Comment by lutzbichler** [comment]
Yes, it does live elsewhere (and this is unlikely to change in the near future). W
