### ISSUE TITLE
vsomeip based spec.

### ISSUE THREAD

**Issue by winet85** [GENIVI/vsomeip#87]
Hello.
I find Autosar Spec Version of vsomeip. I reference web site(http://www.some-ip.com/papers.shtml).
- Which is autosar spec version of vsomeip tag 2.14.16? 
- if vsomeip base on specific version,  Do vsomeip support full function on the spec?

**Comment by lutzbichler** [comment]
vSomeIP supports SOME/IP Service Discovery and SOME/IP-TP. CommonAPI-SomeIP supports the payload serialization/deserialization.
