### ISSUE TITLE
subscribe_notify_test are getting stuck on Renesas hardware

### ISSUE THREAD

**Issue by arcsweety** [GENIVI/vsomeip#89]
Hi,

I am using vsomeip 2.10 version and executing subscribe_notify_test between ubuntu and R-car. But the test case get stuck in the middle . In the logs, get to see error like below.

02:16:07.055551 [info] Notify one event 2222 to client 1111 failed. Event payload not set .

Please provide suggestions to resolve the issue.

**Comment by lutzbichler** [comment]
Please use a more recent version. And, if the problem still persists, provide full logs as well as an ethernet trace.
