### ISSUE TITLE
how to configure client to send request message to server from specific port ?

### ISSUE THREAD

**Issue by navneet01** [GENIVI/vsomeip#95]
how to configure client to send request message to server from specific port

**Comment by lutzbichler** [comment]
By adding a "clients" section to the configuration. The following defines 30401 to be used to communicate to 30501. 

"clients" :
    [
        {
            "reliable_remote_ports"   : { "first" : "30501", "last" : "30501" },
            "unreliable_remote_ports" : { "first" : "30501", "last" : "30501" },
            "reliable_client_ports"   : { "first" : "30401", "last" : "30401" },
            "unreliable_client_ports" : { "first" : "30401", "last" : "30401" }
        }
    ],

Usally, ranges are used. It is currently not supported to define specific client ports for different servers.
