### ISSUE TITLE
is someip supports little endian OR big endian ?

### ISSUE THREAD

**Issue by navneet01** [GENIVI/vsomeip#96]
is someip supports little endian OR big endian ?

**Comment by Siddharthav1** [comment]
I was going through the sourcecode of the SOME/IP. By that study I understood its littleendian. Hope I am not wrong.

**Comment by lutzbichler** [comment]
SOME/IP it self is big endian (on wire). vsomeip supports both, but we currently do not know anyone who is using big endian.
